name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install grunt-cli
        run: npm install -g grunt-cli

      - name: Install local dependencies
        run: npm install

      - name: Run CI build
        run: npm run-script ci

      # - uses: ./.github/actions/build
